###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "ibrahim.naimat@gmail.com",
  "password": "123"
}

###

GET http://localhost:8080/products/seller
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzLGlicmFoaW0ubmFpbWF0QGdtYWlsLmNvbSIsInJvbGVzIjpbImN1c3RvbWVyIl0sImlzcyI6Ik1JVSIsImlhdCI6MTY5ODE3NzU1NiwiZXhwIjoxNjk4MTgxMTU2fQ.KZ94Lvv9_AWSGHI_Wlg17cmkFFueFyHV4yAU6qsq6kYhMCTg0pDSL2Pb2MCPnK9auB4ziGZrmUuGEynAS2MwJQ
Content-Type: application/json

###

GET http://localhost:8080/products/customer
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzLGlicmFoaW0ubmFpbWF0QGdtYWlsLmNvbSIsInJvbGVzIjpbImN1c3RvbWVyIl0sImlzcyI6Ik1JVSIsImlhdCI6MTY5ODE3NzU1NiwiZXhwIjoxNjk4MTgxMTU2fQ.KZ94Lvv9_AWSGHI_Wlg17cmkFFueFyHV4yAU6qsq6kYhMCTg0pDSL2Pb2MCPnK9auB4ziGZrmUuGEynAS2MwJQ
Content-Type: application/json

###

POST http://localhost:8080/bidding/addbid/8/120.0
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzLGlicmFoaW0ubmFpbWF0QGdtYWlsLmNvbSIsInJvbGVzIjpbImN1c3RvbWVyIl0sImlzcyI6Ik1JVSIsImlhdCI6MTY5ODE3NjI1MSwiZXhwIjoxNjk4MTc5ODUxfQ.TckblIx7cR_GlC2BwXrzg2DYIi6kGJCtzvJxFmL4VizJ3Bn-95BFz0N-lWx8J9uX1HvhTSYyzIdmZoLXDZdomQ
