###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "ibrahim.naimat@gmail.com",
  "password": "123"
}

###

GET http://localhost:8080/products/seller
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzLGlicmFoaW0ubmFpbWF0QGdtYWlsLmNvbSIsInJvbGVzIjpbImN1c3RvbWVyIl0sImlzcyI6Ik1JVSIsImlhdCI6MTY5ODE3ODIxOSwiZXhwIjoxNjk4MTgxODE5fQ.8_BQg00AY6NMUlgTMDql5VkKSZcIzlSXbNqB5OSKcXTKtt4ZmQkcmqnYSSEkXkMvb9p9qiU4zjzP5vxnLONuag
Content-Type: application/json

###

GET http://localhost:8080/products/customer
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzLGlicmFoaW0ubmFpbWF0QGdtYWlsLmNvbSIsInJvbGVzIjpbImN1c3RvbWVyIl0sImlzcyI6Ik1JVSIsImlhdCI6MTY5ODE3ODIxOSwiZXhwIjoxNjk4MTgxODE5fQ.8_BQg00AY6NMUlgTMDql5VkKSZcIzlSXbNqB5OSKcXTKtt4ZmQkcmqnYSSEkXkMvb9p9qiU4zjzP5vxnLONuag
Content-Type: application/json

###

POST http://localhost:8080/bidding/addbid/14/130
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0LGlicmFoaW0uYWJ1aGRhaWJAZ21haWwuY29tIiwicm9sZXMiOlsiY3VzdG9tZXIiXSwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTg3MzQ5LCJleHAiOjE2OTgxOTA5NDl9._9iIODH06fxd-IccbQnvwb5X3QpPB7VmdVGzPmu_BBzoCCmqLcG2-YVcP5qHaAHpSL9BKEVIPHBvvf37uoAeIQ
