###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "iabuhdaib@miu.edu",
  "password": "123"
}
###

POST http://localhost:8080/products/addProduct
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLGlhYnVoZGFpYkBtaXUuZWR1Iiwicm9sZXMiOlsiY3VzdG9tZXIiLCJzZWxsZXIiXSwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTk4MTAwLCJleHAiOjE2OTgyMDE3MDB9.jIYoWzFFy3YT0S9GWJsesgQWX8iI7qUVe70hQW4Wvr_xBoViquCAuZzDzsrVLUd_SoR5JPGcMvHMk1ky1DCgAg

{
  "categories": [{"id":1}],
"name": "Test Product 100",
"description": "Test description 100",
"startingPrice" : 100,
"bidDueDate": "2023-10-26",
"paymentDueDate": "2023-10-28"
}


###

PUT http://localhost:8080/products/update
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLGlhYnVoZGFpYkBtaXUuZWR1Iiwicm9sZXMiOlsiY3VzdG9tZXIiLCJzZWxsZXIiXSwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTg2ODQ3LCJleHAiOjE2OTgxOTA0NDd9.nZou5iOMSbsFPBOea2ZVBwjymJka0QtbWrDf5vKOgL3_X6IDUt5x7y6DMhkk1Mz38ep_Ls1Ny4Cr557dCz31YQ

{
  "id": 9,
  "categories": [{"id":1}],
  "name": "product9",
  "description": "product9 description",
  "startingPrice" : 100,
  "bidDueDate": "2023-10-25",
  "paymentDueDate": "2023-10-27"
}

###

POST http://localhost:8080/products/publish/14
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyLGlhYnVoZGFpYkBtaXUuZWR1Iiwicm9sZXMiOlsiY3VzdG9tZXIiLCJzZWxsZXIiXSwiaXNzIjoiTUlVIiwiaWF0IjoxNjk4MTg3MTIwLCJleHAiOjE2OTgxOTA3MjB9.p8BuknRMfzjXooACUa9EjvTMLQo-jVylRqbXPEnhvpxLRIVOeQ4xHi3bPJ99Cff7sWBHQijxklcbXkEsOlogpQ

